!
! Access Switch Configuration
!
hostname switch1
!
vtp mode transparent
!
vlan 10
 name DATA
!
vlan 20
 name VOICE
!
vlan 30
 name MANAGEMENT
!
<PORTS-CONFIGURATION>
!
<SVI-CONFIGURATION>
!
line con 0
 logging synchronous
!
end
